package com.flightontrack.shared;

/**
 * Created by hotvk on 3/17/2018.
 */

public interface Events {
    enum EVENT {
        DEFAULT_EVENT,
        MACT_BIGBUTTON_ONCLICK_START,
        MACT_BIGBUTTON_ONCLICK_STOP,
        MACT_BACKBUTTON_ONCLICK,
        MACT_MULTILEG_ONCLICK,

        FLIGHT_GETNEWFLIGHT_STARTED,
        FLIGHT_GETNEWFLIGHT_COMPLETED,
        FLIGHT_FLIGHTTIME_STARTED,
        FLIGHT_FLIGHTTIME_UPDATE_COMPLETED,
        FLIGHT_CLOSEFLIGHT_COMPLETED,
        FLIGHT_ONSPEEDABOVEMIN,
        FLIGHT_ONSPEEDLOW,
        FLIGHT_ONPOINTSLIMITREACHED,
        FLIGHT_ONSENDCACHECOMPLETED,
        FLIGHT_STATECHANGEDTO_READYTOSAVE,
        FLIGHT_REMOTENUMBER_RECEIVED,
        FLIGHTBASE_GETFLIGHTNUM,

        CLOCK_SERVICESTARTED_MODELOCATION,
        CLOCK_SERVICESELFSTOPPED,
        CLOCK_ONTICK,
        CLOCK_MODECLOCK_ONLY,

        PROP_CHANGED_MULTILEG,
        ROUTE_ONNEW,
        ROUTE_ONLEGLIMITREACHED,
        ROUTE_NOACTIVEROUTE,

        ROUTE_ONRESTART,
        SVCCOMM_ONSUCCESS_NOTIF,
        SVCCOMM_LOCRECCOUNT_NOTZERO,
        SVCCOMM_ONSUCCESS_COMMAND,
        //SVCCOMM_BATCHSIZE_CHANGED,

        SVCCOMM_ONDESTROY,
        SETTINGACT_BUTTONCLEARCACHE_CLICKED,

        SETTINGACT_BUTTONSENDCACHE_CLICKED,
        ALERT_SENTPOINTS,

        ALERT_STOPAPP,
        SQL_TEMPFLIGHTNUM_ALLOCATED,
        SQL_ONCLEARCACHE_COMPLETED,
        SQL_FLIGHTRECORDCOUNT_ZERO
    }
}
